apiVersion: v1
data:
  mapUsers: |
    - userarn: arn:aws:iam::600047163007:user/bahmni-lite-CIUser
      username: bahmni-lite-CIUser
      groups:
        - system:masters
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::600047163007:role/BahmniEKSNodeRole-nonprod
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::600047163007:role/BahmniInfraAdminRoleForIAMUsers
      username: BahmniInfraAdminRoleForIAMUsers
      groups:
        - system:masters
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system